@startuml

' horizontal distance in px
skinparam nodesep 200 

' vertical distance in px
skinparam ranksep 200
'skinparam linetype ortho

skinparam TitleFontSize 100

skinparam State {
  FontSize 80
  FontStyle bold
  ArrowFontSize 50
  ArrowThickness 5
  AttributeFontSize 50
  AttributeFontColor black
}

title State Machine of Sensor Active Object

state Initial {
}

state Sampling {
    Sampling : READ_DATA_SIG
    Sampling : SYNC_CONFIRM_SIG
    state Connected {
    }
    state Disconnected {
    }
}
[*] --> Initial
Initial -r-> Disconnected
Connected -u-> Disconnected : HB_TIMEOUT_SIG
Disconnected -d-> Connected : PACKET_RECEIVED_SIG
'Sampling --> Sampling: READ_DATA, SYNC_CONFIRM

@enduml