@startuml
' Settings
' ============================

' use +,#,- instead of icons
'skinparam classAttributeIconSize 0

' horizontal distance in px
skinparam nodesep 80 

' vertical distance in px
skinparam ranksep 80

' use only straight lines (ortho/polyline)
skinparam linetype ortho

' title
title 1-2-4 UML Objects



' Abstract Classes
' ============================
class MultipleLightBase{
    -Name: String
    #handle: List<SwitchLight*>
    #configHandle: List<ConfigurableLight*>
    +appendSwitchLight()
    +appendConfigurableLight()
    +setupLights()
    +on()
    +off()
}

class SensorBase{
    -ID: Integer
    -Name: String
    #sampling()
    -notify()
    +attach(Observer)
    +detach(Observer)
}

class TriggerSensor_Base{
    #isPressed()
    '#publishTrigger()
    #state: Bool
}

class SamplingSensor_Base{
    #isNewSample()
    '#publishValues()
}

class ControllerBase{
    +ID: Integer
    #Sample: Generic
    +update()
    -checkSwitch(): Bool
    +activate()
    +deactivate()
    #regulate()
    
}

class ConfigurableLight{
    +configure()
}
' Concrete Classes
' ============================
class SwitchLight{
    -state: on/off
    -brightness: 100, const
    #lightID: Integer
    +switch(state: bool)
}

class DimmLight{
    -brightness: Integer
    +configure()
}

class Group{
    '#setBrightness()
    -brightness: Integer
    ': setBrightness()
    +setupLights(): brightness 
    '#regulate(): brightness
}

class Scene{
    '#setLightConfig()
    -lightSettings: List<lightID, brightness>
    +setupLights(): lightSettings
    '#regulate(): lightSettings
}

class DayLightSensor{
    - Lux: Float
}

class HardwareSwitch{
    
}

class SoftwareButton{
    
}

class Clock{
    -Time: Integer
}

'class GroupController{}

'class SceneController{}

class MainController{
    -controllerList: ControllerBase[1..*]
    +update()
    +schedulingSubController()
    +assignEvents()
}

' Instance Example
' ================================
object Example_DinningTable{
}

object Example_CookingScene{
}

object Example_AdaptivePlantLight{
    #regulate()
}

' Relations
' ================================
DimmLight --|> SwitchLight  
DimmLight -u-|> ConfigurableLight  
MultipleLightBase "1..*" o-l-> "1..1"SwitchLight

MultipleLightBase <|-d- Scene
MultipleLightBase <|-d- Group
MultipleLightBase -u-|> ControllerBase

MainController "1..*" o-d-> "1..1" ControllerBase
MainController <-r-o SensorBase
ControllerBase <--o SensorBase

SensorBase <|-- TriggerSensor_Base
SensorBase <|-- SamplingSensor_Base
TriggerSensor_Base <|-- HardwareSwitch
TriggerSensor_Base <|-d- SoftwareButton
SamplingSensor_Base <|-- DayLightSensor
SamplingSensor_Base <|-- Clock

Example_DinningTable -u-|> Group
Example_AdaptivePlantLight -u-|> Group
Example_CookingScene -u-|> Scene

' This is just for better graph allignment
Scene -[hidden]l- SwitchLight
@enduml