@startuml
' Settings
' ============================

' use +,#,- instead of icons
'skinparam classAttributeIconSize 0

' horizontal distance in px
skinparam nodesep 60 

' vertical distance in px
skinparam ranksep 50

' use only straight lines (ortho/polyline)
skinparam linetype ortho

' title
title 3-2-1 Smart Light Factory



' Abstract Classes
' ============================
class Light{
    +update(msg: LightConfig)
}

class Observer{
    +update(msg)
}

class Device{
    -name: String
}

' Concrete Classes
' ============================
class LightManager{
    -_lights: Dict<String, Light> 
    +getLight(name: String)
    +addLight(l: Light)
    +delTrigger(name: String)
}

class SwitchLight{
    +update(msg: LightConfig)
    +switchOn()
    +switchOff()
}

class DimmLight{
    +update(msg: LightConfig)
    +setBrightness(lvl: Percent)
}

class SwitchLightFactory{
    -_lm: LightManager 
    +createLight(name: String)
}

class DimmLightFactory{
    +createLight(name: String)
}


' Relations
' ================================
DimmLightFactory -u-|> SwitchLightFactory
SwitchLightFactory -r-> LightManager
LightManager -r-> Light
Light -u-|> Observer
Light -u-|> Device
SwitchLight -u-|> Light
DimmLight -u-|> SwitchLight


@enduml